<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <brand>
        <headerColor>#0070D2</headerColor>
        <logoVersion>1</logoVersion>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <description>This app provide seamless integration with Cisco Webex Contact Center.</description>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <label>Webex Contact Center</label>
    <navType>Console</navType>
    <tabs>standard-Account</tabs>
    <tabs>standard-Case</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-AppLauncher</tabs>
    <tabs>standard-Task</tabs>
    <tabs>standard-Lead</tabs>
    <tabs>standard-Contract</tabs>
    <tabs>standard-EmailTemplate</tabs>
    <tabs>standard-File</tabs>
    <tabs>standard-Product2</tabs>
    <tabs>standard-Campaign</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>ciscocjs__Cisco_CJS_Agent_Hub_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <fieldName>ParentId</fieldName>
            <tab>standard-Account</tab>
        </mappings>
        <mappings>
            <tab>standard-AppLauncher</tab>
        </mappings>
        <mappings>
            <tab>standard-Campaign</tab>
        </mappings>
        <mappings>
            <fieldName>AccountId</fieldName>
            <tab>standard-Case</tab>
        </mappings>
        <mappings>
            <fieldName>AccountId</fieldName>
            <tab>standard-Contact</tab>
        </mappings>
        <mappings>
            <tab>standard-Contract</tab>
        </mappings>
        <mappings>
            <tab>standard-EmailTemplate</tab>
        </mappings>
        <mappings>
            <tab>standard-File</tab>
        </mappings>
        <mappings>
            <tab>standard-Lead</tab>
        </mappings>
        <mappings>
            <fieldName>AccountId</fieldName>
            <tab>standard-Opportunity</tab>
        </mappings>
        <mappings>
            <tab>standard-Product2</tab>
        </mappings>
        <mappings>
            <tab>standard-Task</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
