/**********************************************************

Class Name : AsyncSoapSforceComSchemasClassLeadservic_TC
Created Date : May 25th, 2015
Created By : Mohit Batwada
Purpoae : Test Class for AsyncSoapSforceComSchemasClassLeadservic

***********************************************************/

@isTest
public class AsyncSoapSforceComSchemasClassLead_TC{
    
    static testMethod void testAsyncSoapSforceComSchemasClassLeadservic(){
        AsyncSoapSforceComSchemasClassLeadservic asoapSForce = new AsyncSoapSforceComSchemasClassLeadservic();
        AsyncSoapSforceComSchemasClassLeadservic.AsyncLeadService asynchLead = new AsyncSoapSforceComSchemasClassLeadservic.AsyncLeadService();
       
    }
}