@isTest

private class FanaticnetWS_TC
{

public static testMethod void FanaticnetWS_TC()
{
    FanaticnetWS ws = new FanaticnetWS ();
    FanaticnetWS.DispatchSaveOperationResponse_element dis = new  FanaticnetWS.DispatchSaveOperationResponse_element();
    FanaticnetWS.FanaticOperation fanop  = new FanaticnetWS.FanaticOperation();
    FanaticnetWS.FanaticOperationResultTransport inst1   =new FanaticnetWS.FanaticOperationResultTransport();
    FanaticnetWS.DispatchLoadOperation_element  inst2   =new FanaticnetWS.DispatchLoadOperation_element();
    FanaticnetWS.ArrayOfFanaticOperationResultTransport     inst3   =new FanaticnetWS.ArrayOfFanaticOperationResultTransport();
    FanaticnetWS.FanaticSaveOperationList inst4   =new FanaticnetWS.FanaticSaveOperationList();
    FanaticnetWS.FanaticBaseOperationList inst5   =new FanaticnetWS.FanaticBaseOperationList();
    FanaticnetWS.FanaticOperationList inst6   =new FanaticnetWS.FanaticOperationList ();
    FanaticnetWS.DispatchSaveOperation_element inst7   =new FanaticnetWS.DispatchSaveOperation_element();
    FanaticnetWS.ArrayOfString inst8   =new FanaticnetWS.ArrayOfString();
    FanaticnetWS.ArrayOfFanaticOperation inst9   =new FanaticnetWS.ArrayOfFanaticOperation();
    FanaticnetWS.DispatchLoadOperationResponse_element inst10  =new FanaticnetWS.DispatchLoadOperationResponse_element();
    FanaticnetWS.FanaticOperationResultsTransport inst11  =new FanaticnetWS.FanaticOperationResultsTransport();
}

}