//========================================================================================================//
//To test the Visualforce controller class Pricing Main{Used For Pricing_above24; Pricing_under24; Pricing_csv_read}
//Created By: Ankur Pradhan
//Created Date: 
//
//Modified By: RMarquardt S-335198 7.17.2015
//Modified Date:
//=======================================================================================================//
@isTest(seealldata=true)
public class Pricingmain_tc 
{

    
   
    
    
  }