@isTest
public class soapQuoteupdate2_TC
{
    static testMethod void soapQuoteupdate2_TC(){
        soapQuoteupdate2 squ =new soapQuoteupdate2();
        soapQuoteupdate2.LogInfo a =new soapQuoteupdate2.LogInfo();
        soapQuoteupdate2.AllowFieldTruncationHeader_element b =new soapQuoteupdate2.AllowFieldTruncationHeader_element();
        soapQuoteupdate2.DebuggingHeader_element c =new soapQuoteupdate2.DebuggingHeader_element();
        soapQuoteupdate2.CallOptions_element  d =new soapQuoteupdate2.CallOptions_element ();
        soapQuoteupdate2.QuoteUpdate e =new soapQuoteupdate2.QuoteUpdate();
        soapQuoteupdate2.ServiceQuote f =new soapQuoteupdate2.ServiceQuote();
        soapQuoteupdate2.QuoteOperation_element  g =new soapQuoteupdate2.QuoteOperation_element();        
        soapQuoteupdate2.SessionHeader_element  h =new soapQuoteupdate2.SessionHeader_element();
        soapQuoteupdate2.QuoteOperationResponse_element qor = new soapQuoteupdate2.QuoteOperationResponse_element();
    
    
    }



}